// This file is generated by update_girlypopdex.py

#ifndef GUARD_CONSTANTS_GIRLYPOPDEX_ENTRIES_H
#define GUARD_CONSTANTS_GIRLYPOPDEX_ENTRIES_H

#include "global.h"

enum GirlypopdexEntries {
    // Season 3
    GIRLYPOPDEX_SHROOMISH = 1,

    // Season 3
    GIRLYPOPDEX_BRELOOM = 2,

    // Season 5
    GIRLYPOPDEX_PANPOUR = 3,

    // Season 5
    GIRLYPOPDEX_SIMIPOUR = 4,

    // Season 6
    GIRLYPOPDEX_VULPIX = 5,

    // Season 6
    GIRLYPOPDEX_NINETALES = 6,

    // Veterans
    GIRLYPOPDEX_CHIKORITA = 7,

    // Veterans
    GIRLYPOPDEX_BAYLEEF = 8,

    // Veterans
    GIRLYPOPDEX_MEGANIUM = 9,

    // Season 4
    GIRLYPOPDEX_PIPLUP = 10,

    // Season 4
    GIRLYPOPDEX_PRINPLUP = 11,

    // Season 4
    GIRLYPOPDEX_EMPOLEON = 12,

    // Season 3
    GIRLYPOPDEX_TREECKO = 13,

    // Season 3
    GIRLYPOPDEX_GROVYLE = 14,

    // Season 3
    GIRLYPOPDEX_SCEPTILE = 15,

    // Season 5
    GIRLYPOPDEX_FENNEKIN = 16,

    // Season 5
    GIRLYPOPDEX_BRAIXEN = 17,

    // Season 5
    GIRLYPOPDEX_DELPHOX = 18,

    // Season 7
    GIRLYPOPDEX_POPPLIO = 19,

    // Season 7
    GIRLYPOPDEX_BRIONNE = 20,

    // Season 7
    GIRLYPOPDEX_PRIMARINA = 21,

    // Season 6
    GIRLYPOPDEX_TORCHIC = 22,

    // Season 6
    GIRLYPOPDEX_COMBUSKEN = 23,

    // Season 6
    GIRLYPOPDEX_BLAZIKEN = 24,

    // Veterans
    GIRLYPOPDEX_WEEDLE = 25,

    // Veterans
    GIRLYPOPDEX_KAKUNA = 26,

    // Veterans
    GIRLYPOPDEX_BEEDRILL = 27,

    // Season 4
    GIRLYPOPDEX_WURMPLE = 28,

    // Season 4
    GIRLYPOPDEX_SILCOON = 29,

    // Season 4
    GIRLYPOPDEX_BEAUTIFLY = 30,

    // Season 6
    GIRLYPOPDEX_CASCOON = 31,

    // Season 6
    GIRLYPOPDEX_DUSTOX = 32,

    // Season 5
    GIRLYPOPDEX_SCATTERBUG = 33,

    // Season 5
    GIRLYPOPDEX_SPEWPA = 34,

    // Season 5
    GIRLYPOPDEX_VIVILLION = 35,

    // Season 5
    GIRLYPOPDEX_LEDYBA = 36,

    // Season 5
    GIRLYPOPDEX_LEDIAN = 37,

    // Season 4
    GIRLYPOPDEX_BIDOOF = 38,

    // Season 4
    GIRLYPOPDEX_BIBAREL = 39,

    // Season 6
    GIRLYPOPDEX_SENTRET = 40,

    // Season 6
    GIRLYPOPDEX_FURRET = 41,

    // Season 5
    GIRLYPOPDEX_BUNNELBY = 42,

    // Season 5
    GIRLYPOPDEX_DIGGERSBY = 43,

    // Season 4
    GIRLYPOPDEX_BUNEARY = 44,

    // Season 4
    GIRLYPOPDEX_LOPUNNY = 45,

    // Season 5
    GIRLYPOPDEX_BURMY = 46,

    // Season 5
    GIRLYPOPDEX_MOTHIM = 47,

    // Season 6
    GIRLYPOPDEX_ODDISH = 48,

    // Season 6
    GIRLYPOPDEX_GLOOM = 49,

    // Season 6
    GIRLYPOPDEX_BELLOSSOM = 50,

    // Season 5
    GIRLYPOPDEX_HOPPIP = 51,

    // Season 5
    GIRLYPOPDEX_SKIPLOOM = 52,

    // Season 5
    GIRLYPOPDEX_JUMPLUFF = 53,

    // Season 7
    GIRLYPOPDEX_CUTIEFLY = 54,

    // Season 7
    GIRLYPOPDEX_RIBOMBEE = 55,

    // Veterans
    GIRLYPOPDEX_NIDORAN_F = 56,

    // Veterans
    GIRLYPOPDEX_NIDORINA = 57,

    // Veterans
    GIRLYPOPDEX_NIDOQUEEN = 58,

    // Season 7
    GIRLYPOPDEX_PIKIPEK = 59,

    // Season 7
    GIRLYPOPDEX_TRUMBREAK = 60,

    // Season 7
    GIRLYPOPDEX_TOUCANNON = 61,

    // Season 3
    GIRLYPOPDEX_SKITTY = 62,

    // Season 3
    GIRLYPOPDEX_DELCATTY = 63,

    // Season 3
    GIRLYPOPDEX_POOCHYENA = 64,

    // Season 3
    GIRLYPOPDEX_MIGHTYENA = 65,

    // Season 3
    GIRLYPOPDEX_WHISMUR = 66,

    // Season 3
    GIRLYPOPDEX_LOUDRED = 67,

    // Season 3
    GIRLYPOPDEX_EXPLOUD = 68,

    // Season 5
    GIRLYPOPDEX_SNUBBULL = 69,

    // Season 5
    GIRLYPOPDEX_GRANBULL = 70,

    // Season 6
    GIRLYPOPDEX_CORSOLA = 71,

    // Season 3
    GIRLYPOPDEX_LOTAD = 72,

    // Season 3
    GIRLYPOPDEX_LOMBRE = 73,

    // Season 3
    GIRLYPOPDEX_LUDICOLO = 74,

    // Season 6
    GIRLYPOPDEX_CLAMPERL = 75,

    // Season 6
    GIRLYPOPDEX_GOREBYSS = 76,

    // Season 5
    GIRLYPOPDEX_FURFROU = 77,

    // Veterans
    GIRLYPOPDEX_ZUBAT = 78,

    // Veterans
    GIRLYPOPDEX_GOLBAT = 79,

    // Veterans
    GIRLYPOPDEX_CROBAT = 80,

    // Season 7
    GIRLYPOPDEX_PICHU = 81,

    // Season 7
    GIRLYPOPDEX_PIKACHU = 82,

    // Season 7
    GIRLYPOPDEX_RAICHU_ALOLA = 83,

    // Season 5
    GIRLYPOPDEX_PLUSLE = 84,

    // Season 4
    GIRLYPOPDEX_PACHIRISU = 85,

    // Season 5
    GIRLYPOPDEX_DEDENNE = 86,

    // Season 7
    GIRLYPOPDEX_MUDBRAY = 87,

    // Season 7
    GIRLYPOPDEX_MUDSDALE = 88,

    // Season 7
    GIRLYPOPDEX_WINGULL = 89,

    // Season 7
    GIRLYPOPDEX_PELIPPER = 90,

    // Season 3
    GIRLYPOPDEX_AZURILL = 91,

    // Season 3
    GIRLYPOPDEX_MARILL = 92,

    // Season 3
    GIRLYPOPDEX_AZUMARILL = 93,

    // Season 7
    GIRLYPOPDEX_STUFFUL = 94,

    // Season 7
    GIRLYPOPDEX_BEWEAR = 95,

    // Season 4
    GIRLYPOPDEX_BUDEW = 96,

    // Season 4
    GIRLYPOPDEX_ROSELIA = 97,

    // Season 4
    GIRLYPOPDEX_ROSERADE = 98,

    // Season 7
    GIRLYPOPDEX_GOLDEEN = 99,

    // Season 7
    GIRLYPOPDEX_SEAKING = 100,

    // Season 7
    GIRLYPOPDEX_BRUXISH = 101,

    // Season 4
    GIRLYPOPDEX_FINNEON = 102,

    // Season 4
    GIRLYPOPDEX_LUMINEON = 103,

    // Veterans
    GIRLYPOPDEX_MAREEP = 104,

    // Veterans
    GIRLYPOPDEX_FLAAFFY = 105,

    // Veterans
    GIRLYPOPDEX_AMPHAROS = 106,

    // Season 7
    GIRLYPOPDEX_MINCCINO = 107,

    // Season 7
    GIRLYPOPDEX_CINCCINO = 108,

    // Season 5
    GIRLYPOPDEX_FLABEBE = 109,

    // Season 5
    GIRLYPOPDEX_FLOETTE = 110,

    // Season 5
    GIRLYPOPDEX_FLORGES = 111,

    // Season 7
    GIRLYPOPDEX_VULPIX_ALOLA = 112,

    // Season 7
    GIRLYPOPDEX_NINETALES_ALOLA = 113,

    // Season 4
    GIRLYPOPDEX_PONYTA = 114,

    // Season 4
    GIRLYPOPDEX_RAPIDASH = 115,

    // Season 7
    GIRLYPOPDEX_MIME_JR = 116,

    // Season 7
    GIRLYPOPDEX_MR_MIME = 117,

    // Season 7
    GIRLYPOPDEX_STARYU = 118,

    // Season 7
    GIRLYPOPDEX_STARMIE = 119,

    // Season 5
    GIRLYPOPDEX_MILTANK = 120,

    // Season 6
    GIRLYPOPDEX_MAROWAK_ALOLA = 121,

    // Season 5
    GIRLYPOPDEX_INKAY = 122,

    // Season 5
    GIRLYPOPDEX_MALAMAR = 123,

    // Veterans
    GIRLYPOPDEX_TOGEPI = 124,

    // Veterans
    GIRLYPOPDEX_TOGETIC = 125,

    // Veterans
    GIRLYPOPDEX_TOGEKISS = 126,

    // Season 4
    GIRLYPOPDEX_EEVEE = 127,

    // Season 5
    GIRLYPOPDEX_SYLVEON = 128,

    // Season 4
    GIRLYPOPDEX_GLACEON = 129,

    // Season 6
    GIRLYPOPDEX_SPINDA = 130,

    // Season 7
    GIRLYPOPDEX_MEOWTH_ALOLA = 131,

    // Season 7
    GIRLYPOPDEX_PERSIAN_ALOLA = 132,

    // Season 6
    GIRLYPOPDEX_SMOOCHUM = 133,

    // Season 6
    GIRLYPOPDEX_JINX = 134,

    // Season 7
    GIRLYPOPDEX_PYUKUMUKU = 135,

    // Season 4
    GIRLYPOPDEX_CLEFFA = 136,

    // Season 4
    GIRLYPOPDEX_CLEFAIRY = 137,

    // Season 4
    GIRLYPOPDEX_CLEFABLE = 138,

    // Season 6
    GIRLYPOPDEX_IGGLYBUFF = 139,

    // Season 6
    GIRLYPOPDEX_JIGGLYPUFF = 140,

    // Season 6
    GIRLYPOPDEX_WIGGLYTUFF = 141,

    // Season 5
    GIRLYPOPDEX_SWIRLIX = 142,

    // Season 5
    GIRLYPOPDEX_SLURPUFF = 143,

    // Season 7
    GIRLYPOPDEX_DITTO = 144,

    // Season 7
    GIRLYPOPDEX_SALANDIT = 145,

    // Season 7
    GIRLYPOPDEX_SALAZZLE = 146,

    // Season 6
    GIRLYPOPDEX_TINKATINK = 147,

    // Season 6
    GIRLYPOPDEX_TINKATUFF = 148,

    // Season 6
    GIRLYPOPDEX_TINKATON = 149,

    // Season 4
    GIRLYPOPDEX_HOUNDOUR = 150,

    // Season 5
    GIRLYPOPDEX_ABSOL = 151,

    // Season 4
    GIRLYPOPDEX_SHELLOS = 152,

    // Season 4
    GIRLYPOPDEX_GASTRODON = 153,

    // Season 6
    GIRLYPOPDEX_GIRAFARIG = 154,

    // Season 6
    GIRLYPOPDEX_FARIGIRAF = 155,

    // Season 7
    GIRLYPOPDEX_BOUNSWEET = 156,

    // Season 7
    GIRLYPOPDEX_STEENEE = 157,

    // Season 7
    GIRLYPOPDEX_TSAREENA = 158,

    // Season 7
    GIRLYPOPDEX_FOMANTIS = 159,

    // Season 7
    GIRLYPOPDEX_LURANTIS = 160,

    // Season 5
    GIRLYPOPDEX_WOOBAT = 161,

    // Season 5
    GIRLYPOPDEX_SWOOBAT = 162,

    // Season 6
    GIRLYPOPDEX_CHINGLING = 163,

    // Season 6
    GIRLYPOPDEX_CHIMECHO = 164,

    // Season 7
    GIRLYPOPDEX_ORICORIO = 165,

    // Season 4
    GIRLYPOPDEX_MISDREAVUS = 166,

    // Season 4
    GIRLYPOPDEX_MISMAGIUS = 167,

    // Season 6
    GIRLYPOPDEX_ELYGEM = 168,

    // Season 6
    GIRLYPOPDEX_BEEHEEYEM = 169,

    // Season 7
    GIRLYPOPDEX_MINIOR__YELLOW_ = 170,

    // Season 7
    GIRLYPOPDEX_MINIOR__PINK_ = 171,

    // Season 5
    GIRLYPOPDEX_LAPRAS = 172,

    // Season 5
    GIRLYPOPDEX_KLEFKI = 173,

    // Season 6
    GIRLYPOPDEX_PORYGON = 174,

    // Season 6
    GIRLYPOPDEX_PORYGON2 = 175,

    // Season 6
    GIRLYPOPDEX_PORYGON_Z = 176,

    // Season 4
    GIRLYPOPDEX_SWABLU = 177,

    // Season 4
    GIRLYPOPDEX_ALTARIA = 178,

    // Season 7
    GIRLYPOPDEX_NOIBAT = 179,

    // Season 7
    GIRLYPOPDEX_NOIVERN = 180,

    // Season 7
    GIRLYPOPDEX_ZORUA = 181,

    // Season 7
    GIRLYPOPDEX_ZOROARK = 182,

    // Season 7
    GIRLYPOPDEX_CASTFORM = 183,

    // Season 6
    GIRLYPOPDEX_LILLEEP = 184,

    // Season 6
    GIRLYPOPDEX_CRADILY = 185,

    // Season 5
    GIRLYPOPDEX_AMAURA = 186,

    // Season 5
    GIRLYPOPDEX_AMAURUS = 187,

    // Season 4
    GIRLYPOPDEX_SNORUNT = 188,

    // Season 4
    GIRLYPOPDEX_FROSLASS = 189,

    // Season 6
    GIRLYPOPDEX_MAWILE = 190,

    // Season 6
    GIRLYPOPDEX_APPLIN = 191,

    // Season 6
    GIRLYPOPDEX_APPLETUN = 192,

    // Season 7
    GIRLYPOPDEX_MIMIKYU = 193,

    // Season 4
    GIRLYPOPDEX_GIBLE = 194,

    // Season 4
    GIRLYPOPDEX_GABITE = 195,

    // Season 4
    GIRLYPOPDEX_GARCHOMP = 196,

    // Season 7
    GIRLYPOPDEX_COSMOG = 197,

    // Season 7
    GIRLYPOPDEX_COSMOEM = 198,

    // Legends
    GIRLYPOPDEX_HAPPINY = 199,

    // Legends
    GIRLYPOPDEX_CHANSEY = 200,

    // Legends
    GIRLYPOPDEX_BLISSEY = 201,

    // Legends
    GIRLYPOPDEX_REGIROCK = 202,

    // Legends
    GIRLYPOPDEX_GARDEVOIR = 203,

    NUM_GIRLYPOPDEX = 203
};

#endif // GUARD_CONSTANTS_GIRLYPOPDEX_ENTRIES_H
